version: 2
executorType: docker
containerInfo:
  - image: node:8
stages:
  build:
    workDir: ~/npm-register
    steps:
      - type: checkout
      - type: cache-restore
        key: npm-register-{{checksum "package.json"}}
      - run: |
          set -x
          node -v
          if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "AWS_SECRET_ACCESS_KEY must be set. Pull requests may only be run by the owner of the repository"
            exit 1
          fi
          yarn
          yarn test
          ./node_modules/.bin/nyc report --reporter=text-lcov > coverage.lcov
          bash <(curl -s https://codecov.io/bash)
          ./node_modules/.bin/standard
      - type: cache-save
        key: cli-engine-{{checksum "package.json"}}
        paths:
          - /usr/local/share/.cache/yarn
          - ~/npm-register/node_modules
